language: csharp
solution: InstaSharper.sln
dotnet: 1.0.3
sudo: required
os: linux
dist: trusty

script:
  - dotnet --info
  - dotnet restore
  - dotnet build
  - cd InstaSharper
  - dotnet pack -o ../nugetpack -c release