version: 1.2.4
os: Visual Studio 2015
platform: Any CPU
configuration: Release

branches:
  only:
    - develop
    - master
skip_commits:
  message: /skip ci/      # Regex for matching commit message

skip_tags: true

build:
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
  include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts
  
build_script:
  - ps: dotnet --info
  - ps: cd InstaSharper
  - ps: dotnet restore
  - ps: dotnet build
  - ps: dotnet pack -o ../nugetpack -c release
  - ps: cd ../InstaSharper.Tests
  - ps: dotnet restore
  - ps: dotnet build
  - ps: dotnet test -parallel none
  - ps: cd ..

environment:
  instaapiuserpassword:
    secure: 7eAl+O5i5BxXWexd26z+wg==

test: off
